

spring:

  datasource:
    username: root
    password: 4188qinwei
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai

mybatis:
  #config-location: classpath:mybatis/sqlConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    root: info
    com.example.blog: debug
  file:
    name: blog/blog.log

server:
  servlet:
    context-path: /blog
  port: 8000


jasypt:
  encryptor:
    password: CodeSheep